query FindExchange($id: ID!) {
  exchange(id: $id) {
    public
    name
    userPermissions {
      id
      user {
        name
        id
        email
        profilePicUrl
      }
      permission
    }
    instruments {
      name
    }
  }
}

mutation AddInstrument(
  $exchangeId: String!
  $instrumentType: String!
  $name: String!
  $positionLimit: Int!
  $tickSize: Int!
) {
  addInstrument(
    exchangeId: $exchangeId
    instrument: {
      instrumentType: $instrumentType
      name: $name
      positionLimit: $positionLimit
      tickSizeMin: $tickSize
    }
  )
}

mutation CreateInvite($exchangeId: String!, $userId: String!) {
  createInvite(
    createInviteInput: { exchangeId: $exchangeId, userId: $userId }
  ) {
    exchangeId
    userId
    id
  }
}

query CheckInvite($id: ID!) {
  checkInvite(id: $id)
}

mutation GenerateApiKey($exchangeId: String!, $forceNew: Boolean!) {
  generateApiKey(exchangeId: $exchangeId, forceNew: $forceNew) {
    apiKey
  }
}

mutation JoinExchange($id: String!) {
  joinExchange(id: $id) {
    exchange {
      id
    }
  }
}

mutation CreateTestExchange {
  createTestExchange {
    id
  }
}

mutation CreateExchange($name: String!, $color: Int!) {
  createExchange(exchangeData: { exchangeColor: $color, exchangeName: $name }) {
    id
    name
    colour
    userPermissions {
      id
    }
  }
}
