query CurrentUser {
  currentUser {
    name
    profilePicUrl
    userPermissions {
      id
      permission
      exchange {
        id
        name
        colour
        instruments {
          name
        }
      }
    }
  }
}

mutation CreateUser($name: String!, $profilePicUrl: String, $id: ID!) {
  createUser(
    createUserInput: { name: $name, profilePicUrl: $profilePicUrl, id: $id }
  ) {
    name
    profilePicUrl
    id
  }
}
