query CurrentUser {
  currentUser {
    name
    profilePicUrl
    userPermissions {
      id
      apiKey
      permission
      exchange {
        id
        name
        colour
        profitLoss {
          profitLoss
        }
        userPermissions {
          id
        }
        instruments {
          name
        }
      }
    }
  }
}

mutation CreateUser(
  $name: String!
  $email: String!
  $profilePicUrl: String
  $id: ID!
) {
  createUser(
    createUserInput: {
      name: $name
      email: $email
      profilePicUrl: $profilePicUrl
      id: $id
    }
  ) {
    name
    email
    profilePicUrl
    id
  }
}
