#!/bin/bash

#colour definitions
red='\e[1;31m'
green='\e[1;32m'
yellow='\e[1;33m'
blue='\e[1;34m'
magenta='\e[1;35m'
cyan='\e[1;36m'
white='\e[0m'

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

printf "%bBuilding SPM C++ Application%b\n" "$magenta" "$white"

docker build -t ubuntu-spm ${SCRIPT_DIR}

status=$?
[ $status -eq 0 ] && echo "$cmd Successfuly synced docker container" || echo "$cmd failed to sync docker container"

docker run --rm -i -v ${PWD}:/spm-build ubuntu-spm

status=$?

[ $status -eq 0 ] && printf "%bBuild complete.\n" "$magenta" "$white" || printf "%bFailed to compile.%b\n" "$red" "$white"
