#!/bin/node

const { exec } = require("child_process");
const { readFileSync, writeFileSync } = require("fs");
const process = require("process");

const [, , command, ...args] = process.argv;

const __deps = __dirname + "/spm-deps";

const basicValidation = (...args) => {
  if (!args.every((a) => a != undefined)) {
    console.log("Missing arguments.");
    process.exit(1);
  }
};

if (command === "build") {
  const [buildScript] = args;
  basicValidation(buildScript);

  const dockerfile = readFileSync(__deps + "/Dockerfile", "utf-8");
  const updatedDockerfile = dockerfile.replace(
    /^CMD .*/gm,
    `CMD ${buildScript}`
  );
  writeFileSync(__deps + "/Dockerfile", updatedDockerfile);

  console.log(`Executing ${`${__deps}/spm-build`}`);

  const application = exec(`sudo ${__deps}/spm-build`);

  application.stdout.on("data", (data) => process.stdout.write(data));
  application.stderr.on("data", (data) => process.stderr.write(data));
}

if (command === undefined) {
  console.log("No command specified. Try 'spm build ./debug.sh`");
}
