name: Merge Actions

on:
  push:
    branches: [main]

jobs:
  exchange:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Install C++ Dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ rsync zip openssh-server make cmake autoconf automake libtool curl unzip protobuf-compiler libprotobuf-dev libprotoc-dev libboost-all-dev ninja-build libpq-dev postgresql-server-dev-all libpqxx-dev

      - name: Build Exchange
        working-directory: ./apps/exchange
        run: ./release.sh

      - name: Execute Tests
        working-directory: ./apps/exchange
        run: ./build/unit_test

      - name: Upload Exchange
        uses: actions/upload-artifact@v3
        with:
          name: exchange
          path: ./apps/exchange/build/exchange

      - name: Upload Exchange Unit Tests
        uses: actions/upload-artifact@v3
        with:
          name: unit_test
          path: ./apps/exchange/build/unit_test

  javascript:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: NPM Install
        run: npm ci

      - name: Build JavaScript
        run: npm run build

      - name: Upload JavaScript Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: JavaScript Output
          path: |
            ./dist/apps/*
            !./dist/apps/frontend/.next/cache
